### ISSUE TITLE
change domain names to lowercase

### ISSUE THREAD

**Issue by uhoreg** [f0x52/fed-tester#1]
If the domain name is typed with any capital letters (because tablet), then MatchingServerName returns an error.  Since domain names are case insensitive, the input should be converted to lowercase.
![screenshot_20180515-224038](https://user-images.githubusercontent.com/1012976/40093684-542ceeee-5891-11e8-9f7b-2f647a2aa307.jpg)

**Comment by f0x52** [comment]
this sounds more like a backend issue, but I'll add a `.toLowerCase()`
